// next/app/1-routing/products/page.tsx
// เป็นส่วนหนึ่งของ Server Components จึงสามารถใช้ Component async function ได้
// เพราะตามปกติของ React เราจะไม่นสามารถใช้ Component async function ได้

import { Metadata } from "next"
import { getProducts } from "../lib/products"

export const metadata: Metadata = {
  title: "Products",
  description: "Explore the products available in our store"
}

export default async function Page() {
  const products = await getProducts()
  return (
    <div>
      <h1 className="text-xl font-bold mb-2">All Products</h1>
      <a href="/1-routing" className="text-blue-600 underline mb-4 inline-block">
        Back to main routing
      </a>
      <ul className="pl-5 list-disc space-y-1">
        {products.map((product) => (
          <li key={product.id}>
            <a href={`/1-routing/products/${product.id}`} className="text-blue-600 underline">
              (ID: {product.id}) {product.title}
            </a>
          </li>
        ))}
      </ul>
    </div>
  )
}

// svelte/src/routes/9-routing/products/+page.svelte
<script lang="ts">
  import type { PageProps } from "./$types";

  let props: PageProps = $props()
</script>

<h1 class="text-xl font-bold">Product list</h1>

<a href="/9-routing/products/new" class="text-blue-700 underline">Create new product</a>

<ul class="list-disc pl-6 mt-3">
  {#each props.data.products as product}
    <li><a href={`/9-routing/products/${product.id}`} class="text-blue-700 underline">{product.title} - ${product.price}</a></li>
  {/each}
</ul>
