// backend/hono/todo-tsx/src/routes/signUp.tsx
import { Hono } from 'hono'
import storeAuth from '../middleware/storeAuth.js'
import { ShowNotification } from '../components/ShowNotification.js'
import { zValidator } from '../utils/zValidator.js'
import { z } from 'zod'
import { auth } from '../auth.js'
import { makeNotification } from '../utils/notification.js'

const app = new Hono()

app.get('/', storeAuth, (c) => {
  const user = c.get('user')
  if (user) {
    return c.redirect('/')
  }
  return c.render(
    <>
      <div className="container" style={{ maxWidth: '360px' }}>
        <h1 className="mt-4">Sign-up</h1>
        <hr />
        <ShowNotification context={c}></ShowNotification>
        <form action="/sign-up" method="post">
          <div className="mb-3">
            <label htmlFor="name" className="form-label">Name</label>
            <input type="text" className="form-control" id="name" name="name" required />
          </div>
          <div className="mb-3">
            <label htmlFor="email" className="form-label">Email address</label>
            <input type="email" className="form-control" id="email" name="email" aria-describedby="emailHelp" required />
          </div>
          <div className="mb-3">
            <label htmlFor="password" className="form-label">Password</label>
            <input type="password" className="form-control" id="password" name="password" required />
          </div>
          <div className="mb-3">
            <label htmlFor="passwordConfirm" className="form-label">Password Confirm</label>
            <input type="password" className="form-control" id="passwordConfirm" name="passwordConfirm" required />
          </div>
          <button type="submit" className="btn btn-primary w-100">Submit</button>
        </form>
        <p class="mt-3">
          Already have an account? <a href="/login">Login</a>
        </p>
      </div>
    </>
  )
})

const validator = zValidator(z.object({
  name: z.string({ message: 'Name is required' }).min(1, { message: 'Name is required' }),
  email: z.string({ message: 'Email is required' }).email({ message: 'Invalid email' }),
  password: z.string({ message: 'Password is required' }).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/, {
    message: 'Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one number, and one special character.'
  }),
  passwordConfirm: z.string({ message: 'Password confirmation is required' }),
}).superRefine(({ password, passwordConfirm }, ctx) => {
  if (password !== passwordConfirm) {
    ctx.addIssue({
      code: 'custom',
      message: 'Passwords do not match'
    })
  }
}))

app.post('/', validator, async (c) => {
  const data = await c.req.valid('form')
  await auth.api.signUpEmail({
    body: data
  })
  makeNotification(c, ['Sign-up successful. You can login now.'])
  return c.redirect('/login')
})

export default app

// backend/todo-frontend/pages/sign-up.vue
<script setup lang="ts">
import { z } from 'zod'
import { toTypedSchema } from '@vee-validate/zod'

definePageMeta({
  layout: 'auth'
})

const auth = useAuth()
const { errors, handleSubmit, defineField } = useForm({
  validationSchema: toTypedSchema(z.object({
    name: z.string({ message: 'Name is required' }).min(1, { message: 'Name is required' }),
    email: z.string({ message: 'Email is required' }).email({ message: 'Invalid email' }),
    password: z.string({ message: 'Password is required' }).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/, {
      message: 'Password must be strong and contain at least 8 characters, an uppercase letter, a lowercase letter, a number, and a special character'
    }),
    confirmPassword: z.string({ message: 'Confirm password is required' }).min(1, { message: 'Confirm password is required' })
  }).superRefine(({ password, confirmPassword }, ctx) => {
    if (password !== confirmPassword) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: 'Passwords do not match',
        path: ['confirmPassword']
      })
    }
  }))
})

const [name, nameAttrs] = defineField('name', {
  validateOnModelUpdate: false
})

const [email, emailAttrs] = defineField('email', {
  validateOnModelUpdate: false
})

const [password, passwordAttrs] = defineField('password', {
  validateOnModelUpdate: false
})

const [confirmPassword, confirmPasswordAttrs] = defineField('confirmPassword', {
  validateOnModelUpdate: false
})

const router = useRouter()
const notification = useNotification()

const onSubmitError = ref<string | null>(null)
const onSubmit = handleSubmit(async (values) => {
  try {
    const res = await auth.signUp.email(values)
    if (res.error) {
      throw new Error(res.error.message)
    }
    notification.setMessage('Sign up successful. You can login now.')
    router.push('/login')
  } catch (error) {
    onSubmitError.value = (error as Error).message
  }
})
</script>

<template>
  <div class="mt-6 shadow-xl p-6 rounded-md">
    <h1 class="text-xl font-bold">Sign Up</h1>
    <ShowNotification :errors="errors" class="mt-4"></ShowNotification>
    <ShowNotification :errors="onSubmitError" class="mt-4"></ShowNotification>
    <form class="mt-6" @submit.prevent="onSubmit">
      <div class="mb-4">
        <label for="name" class="block font-medium text-gray-700">Name:</label>
        <input v-model="name" v-bind="nameAttrs" type="text" id="name" name="name" class="input mt-1" />
      </div>
      <div class="mb-4">
        <label for="email" class="block font-medium text-gray-700">Email:</label>
        <input v-model="email" v-bind="emailAttrs" type="email" id="email" name="email" class="input mt-1" />
      </div>
      <div class="mb-4">
        <label for="password" class="block font-medium text-gray-700">Password:</label>
        <input v-model="password" v-bind="passwordAttrs" type="password" id="password" name="password" class="input mt-1" />
      </div>
      <div class="mb-4">
        <label for="confirmPassword" class="block font-medium text-gray-700">Confirm Password:</label>
        <input v-model="confirmPassword" v-bind="confirmPasswordAttrs" type="password" id="confirmPassword" name="confirmPassword" class="input mt-1" />
      </div>
      <button type="submit" class="btn w-full mt-2">
        Sign Up
      </button>
    </form>
    <div class="mt-4">
      <p>
        Already have an account? <NuxtLink to="/login" class="underline text-blue-600">Login</NuxtLink>
      </p>
    </div>
  </div>
</template>
