// svelte/src/routes/1-state/ThemeSwitcher.svelte
<script lang="ts">
  import { theme } from "./theme.svelte"
</script>

<div class="space-x-2">
  <label>
    <input type="radio" name="theme" value="light" checked={theme.value === 'light'} oninput={() => theme.value = 'light'} />
    Light
  </label>
  <label>
    <input type="radio" name="theme" value="dark" checked={theme.value === 'dark'} oninput={() => theme.value = 'dark'} />
    Dark
  </label>
</div>

// vue/provider/src/components/ThemeSwitcher.vue
<script setup lang="ts">
import { defineModel } from 'vue'

const theme = defineModel()
</script>

<template>
  <div class="space-x-6 p-3 rounded shadow-md border border-gray-300 inline-block">
    <label>
      <input v-model="theme" type="radio" value="light">
      <span>☀️ Light</span>
    </label>
    <label>
      <input v-model="theme" type="radio" value="dark">
      <span>🌙 Dark</span>
    </label>
    <label>
      <input v-model="theme" type="radio" value="fancy">
      <span>🌈 Fancy</span>
    </label>
  </div>
</template>
